version: "3.4"
services:
  blockchain:
    image: trase/blockchain-event-broker
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    links:
      - virtuoso:database
    ports:
      - "8888:80"
    volumes:
      - "/Users/mauricedalderup/dev/trase/LBLOD/lblod-blockchain-event-broker:/app/"
  blockchainNotifier:
    image: lblod/blockchain-informing-service
    restart: always
    links:
      - virtuoso:database
      - blockchain:blockchain
  decisionservice:
    image: trase/decision-service
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
      MONGO_URI: ${MONGO_URI}
    links:
      - virtuoso:database
    volumes:
      - "/Users/mauricedalderup/dev/trase/LBLOD/lblod-decision-service:/app/"
      - "/Users/mauricedalderup/dev/trase/LBLOD/network/artifacts/clients/:/clients/"
      - "/Users/mauricedalderup/dev/trase/LBLOD/network/artifacts/config/:/config/"
      - "/Users/mauricedalderup/dev/trase/LBLOD/certs/:/usr/src/app/certs/"
  authentication:
    image: trase/authentication-service
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
    volumes:
      - "/Users/mauricedalderup/dev/trase/LBLOD/lblod-authentication-integration-service:/app/"
      - "/Users/mauricedalderup/dev/trase/LBLOD/network/artifacts/clients/:/clients/"
      - "/Users/mauricedalderup/dev/trase/LBLOD/network/artifacts/config/:/config/"
  frontend:
    image: trase/frontend-local
    ports:
      - "82:1234"
    volumes:
      - "/Users/mauricedalderup/dev/trase/LBLOD/lblod-frontend:/usr/src/app/"
